require("mason").setup()
require("mason-lspconfig").setup()

vim.lsp.enable("lua_ls")
vim.lsp.enable("rust-analyzer")
vim.lsp.enable("clangd")
vim.lsp.enable("html")
vim.lsp.enable("ts_ls")
vim.lsp.enable("jsonls")
vim.lsp.enable("pyright")
vim.lsp.enable("cssls")
