return {
	-- {
	-- 	'rmagatti/auto-session',
	-- 	lazy = false,
	--
	-- 	---enables autocomplete for opts
	-- 	---@module "auto-session"
	-- 	---@type AutoSession.Config
	-- 	opts = {
	-- 		enabled = true,
	-- 		auto_save = true,
	-- 		auto_restore = true,
	-- 		auto_create = true,
	-- 		use_git_branch = true,
	-- 		lazy_support = true,
	-- 		close_unsupported_windows = true,
	-- 		cwd_change_handling = true,
	-- 		suppressed_dirs = { '~/', '~/Sources', '~/Downloads', '/', '~/Documents' },
	-- 		-- log_level = 'debug',
	-- 	}
	-- }
}
