schema_version = "1.0.0"
id = "material_library"
name = "Material Library"
version = "0.6.0"
tagline = "Material Library VX"
maintainer = "Community"
type = "add-on"
tags = ["Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/materials_library_vx"
copyright = ["2024 Mackraken"]
